### ISSUE TITLE
deprecated warnings

### ISSUE THREAD

**Issue by wrshoemaker** [jonchang/homebrew-biology#2]
Hello,

I'm installing treePL using brew and the brew output asked me to send the following error. Thank you for maintaining this resource. 

`Warning: Calling 'depends_on :mpi' is deprecated!`
`Use 'depends_on "open-mpi"' instead.`
`/usr/local/Homebrew/Library/Taps/jonchang/homebrew-biology/Formula/revbayes.rb:11:in `<class:Revbayes>`
`Please report this to the jonchang/biology tap!`

`Warning: Calling 'depends_on :mpi' is deprecated!`
`Use 'depends_on "open-mpi"' instead.`
`/usr/local/Homebrew/Library/Taps/jonchang/homebrew-biology/Formula/examl.rb:10:in <class:Examl>`
`Please report this to the jonchang/biology tap!`

`Warning: Calling 'depends_on :mpi' is deprecated!`
`Use 'depends_on "open-mpi"' instead.`
`/usr/local/Homebrew/Library/Taps/jonchang/homebrew-biology/Formula/phylobayes-mpi.rb:6:in <class:PhylobayesMpi>`
`Please report this to the jonchang/biology tap!`

**Comment by jonchang** [comment]
Hi Will, I'm working on this now. Feel free to bug me if I don't get this up and running in say a week. @wrshoemaker

**Comment by jonchang** [comment]
@wrshoemaker treepl now lives in https://github.com/brewsci/homebrew-bio, so please file issues there if you encounter problems. I will update the treepl wiki momentarily
