### ISSUE TITLE
Warning: Calling depends_on :java is deprecated

### ISSUE THREAD

**Issue by Cactusolo** [jonchang/homebrew-biology#42]
Hi,
when I ran `brew update && brew upgrade`, I came across these lines, so I report here as suggested:

==> Deleted Casks
master-password
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the jonchang/biology tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/jonchang/homebrew-biology/Formula/illumiprocessor.rb:8

**Comment by jonchang** [comment]
Thanks for reporting this Miao.
