### ISSUE TITLE
Error 1 on `brew install phylobayes`

### ISSUE THREAD

**Issue by plannapus** [jonchang/homebrew-biology#8]
I have been trying to install phylobayes through your formula but gets this error:

```
g++ -c -Wall -O3 -fpermissive   ReadSample.cpp
PB.cpp:1096:11: error: qualified reference to 'Random' is a constructor name rather than a type in this context
                Random::Random(1001);
                        ^
1 error generated.
make: *** [PB.o] Error 1
make: *** Waiting for unfinished jobs....
```

Any idea on what's going on?
I am on MacOsX 10.13.6.

For reference, i'm trying to install it this way because one of the pre-compiled macosx binaries they provide does not work on my machine (`readdiv`) and it seems to be a dependency issue, so I thought the formula would make a better job at compiling it.

**Comment by jonchang** [comment]
@plannapus please report this bug to the phylobayes developer. Their code is doing something strange. All I do is package the software.

**Comment by plannapus** [comment]
Ok! Thanks.

**Comment by jonchang** [comment]
It does seem to succeed on Linux so if you have access to a Linux machine (or can set up Docker on your Mac) you can use that while I figure this out.

**Comment by plannapus** [comment]
Thanks for checking it. I do have access to a Linux so i ll try there. I contacted the phylobayes developer with all the details on the errors (the one on the precompiled version and the one that happens during compilation), will update when/if he answers. Thanks again!

**Comment by jonchang** [comment]
should work on mac now: https://github.com/jonchang/homebrew-biology/pull/9

**Comment by jonchang** [comment]
Please continue to follow up with the phylobayes developer as this patch seems quite fragile. Thanks for the report.

**Comment by plannapus** [comment]
I just received an answer from the developer who notified me that the version of the code present on megasun at montreal is obsolete. The current version (4.1d) is the one present on their github page: http://github.com/bayesiancook/phylobayes and indeed the code compiles ok. Thanks for your previous fix though!
